presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
          command:
            - "pre-commit"
            - "run"
            - "--all-files"

  - name: import-test
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/import-test
    spec:
      containers:
        - image: quay.io/thoth-station/s2i-generic-data-science-notebook:latest
          command:
            - /bin/sh
            - '-c'
            - >-
              pip install papermill && papermill -k python
              "tests/test.ipynb" -
